[tool.black]
line-length = 88
target-version = ['py36', 'py37', 'py38', 'py39']
include = '\.pyi?$'
extend-ignore = 'E203'

[tool.isort]
profile = 'black'
skip_gitignore = true
skip='migrations'

[mypy]
python_version = '3.6'
allow_redefinition = true
check_untyped_defs = true
show_error_codes = true
warn_unused_ignores = true
strict_optional = true
incremental = true
warn_redundant_casts = true
warn_unused_configs = true
local_partial_types = true
show_traceback = true
strict=true
